# Generated by Django 4.2 on 2023-05-06 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
